#
# Builder
#

FROM --platform=$BUILDPLATFORM golang:1.26.5-alpine as builder

# use version (for example "v0.3.3") or "main"
ARG WATCHTOWER_VERSION=main
ARG WATCHTOWER_BUILD_VERSION=dev
ARG TARGETOS
ARG TARGETARCH

# Pre download required modules to avoid redownloading at each build thanks to docker layer caching.
# Copying go.mod and go.sum ensure to invalid the layer/build cache if there is a change in module requirement
WORKDIR /watchtower
COPY go.mod .
COPY go.sum .
RUN go mod download

RUN apk add --no-cache \
    alpine-sdk \
    ca-certificates \
    git \
    tzdata

COPY . /watchtower

RUN \
  cd /watchtower && \
  GO111MODULE=on CGO_ENABLED=0 GOOS="${TARGETOS:-linux}" GOARCH="$TARGETARCH" go build -v -ldflags "-s -w -X github.com/containrrr/watchtower/internal/meta.Version=$WATCHTOWER_BUILD_VERSION" .


#
# watchtower
#

FROM scratch

LABEL "com.centurylinklabs.watchtower"="true"

# copy files from other container
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=builder /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=builder /watchtower/watchtower /watchtower

HEALTHCHECK CMD [ "/watchtower", "--health-check"]

ENTRYPOINT ["/watchtower"]
